# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - discordstorage

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Install dependencies, update browserslist, fix vulnerabilities, and build
      - name: npm install, update, audit fix, and build
        run: |
          npm install
          npx browserslist@latest --update-db
          npm audit fix --force
          CI=false npm run build --if-present
          npm run test --if-present

      # Zip artifact for deployment
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      # Upload artifact for deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      # Download artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Unzip artifact for deployment
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Login to Azure using service principal
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_58910E6AF2A547859947BAF7AF02130A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A6357FB51AF64F3DB2AF645F0AA3D0BD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_102E06A2B09941B7869207E295D4644D }}

      # Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'discordstorage'
          slot-name: 'Production'
          package: .
